name: build and push rag image
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build image
        run: docker build -t ${{ secrets.DOCKER_USER }}/rag:${{ github.sha }} -f backend/Dockerfile .

      - name: scan rag image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/rag:${{ github.sha }}
          format: table
          severity: 'HIGH,CRITICAL'

      - name: docker push image
        run: docker push ${{ secrets.DOCKER_USER }}/rag:${{ github.sha }}
